# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches:
      - '**'
      - '!snapshot-patch-**'
      - '!main'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout package
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn' # or npm
      - name: Install Dependency
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Lint Style
        run: yarn lintStyle
      - name: Building production site
        run: yarn run export
        env:
          NEXT_PUBLIC_EMAILJS_USER_ID: ${{secrets.EJS_USER_ID}}
          NEXT_PUBLIC_EMAILJS_SERVICE_ID: ${{secrets.EJS_SERVICE_ID}}
          NEXT_PUBLIC_EMAILJS_TEMPLATE_ID: ${{secrets.EJS_TEMPLATE_ID}}
          NODE_ENV: production
