# Resources: https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - name: Checkout package
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependency
        run: yarn install --frozen-lockfile
      - name: Building production site
        run: yarn run build
        env:
          NODE_ENV: production
      - name: Deploying to firebase preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHUBY_MAO }}'
          channelId: live
          projectId: shuby-mao
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
