name: Integration Test

on:
  pull_request:
    branches: [main]

jobs:
  e2etest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout package
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn' # or npm
      - name: Install Dependency
        run: yarn install --frozen-lockfile
      - name: Install Playwright browser
        run: npx playwright install --with-deps
      - name: Run End to End Test
        run: yarn build && yarn test:report
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: tests/playwright-report/*