name: notion-bot-pull-request

on:
  push:
    branches:
      - 'notion-dev'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout package
        uses: actions/checkout@v3
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT }}
          branch: notion-dev
          destination_branch: main
          delete-branch: false
          pr_title: 'Upate Notion Notes'
          pr_body: |
            Upate Notion Notes
      - name: Check outputs
        run: |
          echo "Pull Request Number - echo ${{steps.open-pr.outputs.pr_number}}"
          echo "Pull Request URL - ${{steps.open-pr.outputs.pr_url}}"
